using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChickenNuget
{
    internal static class AsciiGraceful
    {
        internal static readonly string alphabetKey =
                @"0123456789" +
                @"abcdefghijklmnopqrstuvwxyz" +
                @"!""$%^&*()_+{ }:@~<>?" +
                @"[];'#,./" +
                @"\|";

        internal static readonly string GracefulRaw = GetAsciiGraceful();

        private static string GetAsciiGraceful()
        {
            var sb = new StringBuilder();

            sb.AppendLine(@"  __  ");
            sb.AppendLine(@" /  \ ");
            sb.AppendLine(@"(  0 )");
            sb.AppendLine(@" \__/ ");
            sb.AppendLine(@"  __  ");
            sb.AppendLine(@" /  \ ");
            sb.AppendLine(@"(_/ / ");
            sb.AppendLine(@" (__) ");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(___ \");
            sb.AppendLine(@" / __/");
            sb.AppendLine(@"(____)");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"( __ \");
            sb.AppendLine(@" (__ (");
            sb.AppendLine(@"(____/");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" / _ \");
            sb.AppendLine(@"(__  (");
            sb.AppendLine(@"  (__/");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" / __)");
            sb.AppendLine(@"(___ \");
            sb.AppendLine(@"(____/");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" / __)");
            sb.AppendLine(@"(  _ \");
            sb.AppendLine(@" \___/");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(__  )");
            sb.AppendLine(@"  / / ");
            sb.AppendLine(@" (_/  ");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"/ _  \");
            sb.AppendLine(@") _  (");
            sb.AppendLine(@"\____/");
            sb.AppendLine(@" ___  ");
            sb.AppendLine(@"/ _ \ ");
            sb.AppendLine(@"\__  )");
            sb.AppendLine(@"(___/ ");
            sb.AppendLine(@"  __  ");
            sb.AppendLine(@" / _\ ");
            sb.AppendLine(@"/    \");
            sb.AppendLine(@"\_/\_/");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(  _ \");
            sb.AppendLine(@" ) _ (");
            sb.AppendLine(@"(____/");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" / __)");
            sb.AppendLine(@"( (__ ");
            sb.AppendLine(@" \___)");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(    \");
            sb.AppendLine(@" ) D (");
            sb.AppendLine(@"(____/");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(  __)");
            sb.AppendLine(@" ) _) ");
            sb.AppendLine(@"(____)");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(  __)");
            sb.AppendLine(@" ) _) ");
            sb.AppendLine(@"(__)  ");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" / __)");
            sb.AppendLine(@"( (_ \");
            sb.AppendLine(@" \___/");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"/ )( \");
            sb.AppendLine(@") __ (");
            sb.AppendLine(@"\_)(_/");
            sb.AppendLine(@"  __  ");
            sb.AppendLine(@" (  ) ");
            sb.AppendLine(@"  )(  ");
            sb.AppendLine(@" (__) ");
            sb.AppendLine(@"   __ ");
            sb.AppendLine(@" _(  )");
            sb.AppendLine(@"/ \) \");
            sb.AppendLine(@"\____/");
            sb.AppendLine(@" __ _ ");
            sb.AppendLine(@"(  / )");
            sb.AppendLine(@" )  ( ");
            sb.AppendLine(@"(__\_)");
            sb.AppendLine(@" __   ");
            sb.AppendLine(@"(  )  ");
            sb.AppendLine(@"/ (_/\");
            sb.AppendLine(@"\____/");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"( \/ )");
            sb.AppendLine(@"/ \/ \");
            sb.AppendLine(@"\_)(_/");
            sb.AppendLine(@" __ _ ");
            sb.AppendLine(@"(  ( \");
            sb.AppendLine(@"/    /");
            sb.AppendLine(@"\_)__)");
            sb.AppendLine(@"  __  ");
            sb.AppendLine(@" /  \ ");
            sb.AppendLine(@"(  O )");
            sb.AppendLine(@" \__/ ");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(  _ \");
            sb.AppendLine(@" ) __/");
            sb.AppendLine(@"(__)  ");
            sb.AppendLine(@"  __  ");
            sb.AppendLine(@" /  \ ");
            sb.AppendLine(@"(  O )");
            sb.AppendLine(@" \__\)");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(  _ \");
            sb.AppendLine(@" )   /");
            sb.AppendLine(@"(__\_)");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"/ ___)");
            sb.AppendLine(@"\___ \");
            sb.AppendLine(@"(____/");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(_  _)");
            sb.AppendLine(@"  )(  ");
            sb.AppendLine(@" (__) ");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"/ )( \");
            sb.AppendLine(@") \/ (");
            sb.AppendLine(@"\____/");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"/ )( \");
            sb.AppendLine(@"\ \/ /");
            sb.AppendLine(@" \__/ ");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"/ )( \");
            sb.AppendLine(@"\ /\ /");
            sb.AppendLine(@"(_/\_)");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"( \/ )");
            sb.AppendLine(@" )  ( ");
            sb.AppendLine(@"(_/\_)");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"( \/ )");
            sb.AppendLine(@" )  / ");
            sb.AppendLine(@"(__/  ");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(__  )");
            sb.AppendLine(@" / _/ ");
            sb.AppendLine(@"(____)");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" / \  ");
            sb.AppendLine(@" \_/  ");
            sb.AppendLine(@" (_)  ");
            sb.AppendLine(@"  _ _ ");
            sb.AppendLine(@" (/(/ ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"/ (__)");
            sb.AppendLine(@"\__  \");
            sb.AppendLine(@"(__)_/");
            sb.AppendLine(@" _ _  ");
            sb.AppendLine(@"(// ) ");
            sb.AppendLine(@" / /_ ");
            sb.AppendLine(@"(_/(/ ");
            sb.AppendLine(@"  __  ");
            sb.AppendLine(@" /  \ ");
            sb.AppendLine(@"(_/\_)");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" ( _ \");
            sb.AppendLine(@"/ _  /");
            sb.AppendLine(@"\__\_)");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"(\/\/)");
            sb.AppendLine(@" )  ( ");
            sb.AppendLine(@"(/\/\)");
            sb.AppendLine(@"   _  ");
            sb.AppendLine(@"  / ) ");
            sb.AppendLine(@" ( (  ");
            sb.AppendLine(@"  \_) ");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" ( \  ");
            sb.AppendLine(@"  ) ) ");
            sb.AppendLine(@" (_/  ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@" ____ ");
            sb.AppendLine(@"(____)");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" ( )  ");
            sb.AppendLine(@"(_ _) ");
            sb.AppendLine(@" (_)  ");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" (  _)");
            sb.AppendLine(@"(_ (_ ");
            sb.AppendLine(@" (___)");
            sb.AppendLine(@" ___  ");
            sb.AppendLine(@"(_  ) ");
            sb.AppendLine(@" _) _)");
            sb.AppendLine(@"(___) ");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" (_)  ");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" (_)  ");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" /   \");
            sb.AppendLine(@"( (__/");
            sb.AppendLine(@" \___)");
            sb.AppendLine(@" __   ");
            sb.AppendLine(@"(_ \_ ");
            sb.AppendLine(@"  \__)");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"   __ ");
            sb.AppendLine(@"  / / ");
            sb.AppendLine(@" ( (  ");
            sb.AppendLine(@"  \_\ ");
            sb.AppendLine(@" __   ");
            sb.AppendLine(@" \ \  ");
            sb.AppendLine(@"  ) ) ");
            sb.AppendLine(@" /_/  ");
            sb.AppendLine(@" ___  ");
            sb.AppendLine(@"(__ \ ");
            sb.AppendLine(@" (__/ ");
            sb.AppendLine(@" (_)  ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@" ___  ");
            sb.AppendLine(@"(___) ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@" ___  ");
            sb.AppendLine(@"(___) ");
            sb.AppendLine(@" ___  ");
            sb.AppendLine(@"(___) ");
            sb.AppendLine(@" ___  ");
            sb.AppendLine(@"/  _) ");
            sb.AppendLine(@") (_  ");
            sb.AppendLine(@"\___) ");
            sb.AppendLine(@"  ___ ");
            sb.AppendLine(@" (_  \");
            sb.AppendLine(@"  _) (");
            sb.AppendLine(@" (___/");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" (_)  ");
            sb.AppendLine(@" ( )  ");
            sb.AppendLine(@" (/   ");
            sb.AppendLine(@"   _  ");
            sb.AppendLine(@"  (/  ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@" _  _ ");
            sb.AppendLine(@"/ )( \");
            sb.AppendLine(@")    (");
            sb.AppendLine(@"\_)(_/");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" ( )  ");
            sb.AppendLine(@" (/   ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"      ");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" (_)  ");
            sb.AppendLine(@"   _  ");
            sb.AppendLine(@"  / ) ");
            sb.AppendLine(@" / /  ");
            sb.AppendLine(@"(_/   ");
            sb.AppendLine(@" _    ");
            sb.AppendLine(@"( \   ");
            sb.AppendLine(@" \ \  ");
            sb.AppendLine(@"  \_) ");
            sb.AppendLine(@"  _   ");
            sb.AppendLine(@" ( \  ");
            sb.AppendLine(@" / /  ");
            sb.AppendLine(@" \_)  ");

            return sb.ToString();
        }
    }
}
